### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by EleDiaz** [ULL-ESIT-GRADOII-PL/eliminacion-del-switch-juan-fran-2-0#3]
Actualicen el Readme un poco es el mismo de hace 2 prácticas, no hay issues, ninguno.
En cuanto al uso del linter, no se usó mucho en los ficheros /assets/js/*, recomendaría que lo pasasen y  los mirasen.

**Comment by 0fprod** [comment]
Actualizado el readme
